homeassistant: true
mqtt:
  server: mqtt://192.168.178.20
  user: mqtt-user
  password: !secret zigbee2mqtt_password
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  port: 8099
devices:
  '0x7cb03eaa0a04b7f7':
    friendly_name: office_ceiling
  '0xf0d1b8000011acc3':
    friendly_name: livingroom_ceiling_1
  '0xf0d1b8000011b4ee':
    friendly_name: livingroom_ceiling_2
  '0xf0d1b8000011ac5b':
    friendly_name: livingroom_ceiling_3
  '0xf0d1b800001199b1':
    friendly_name: livingroom_ceiling_4
  '0xf0d1b8000019a7d9':
    friendly_name: livingroom_floorlamp
  '0xf0d1b8000019a7ba':
    friendly_name: kitchen_ceiling
  '0x680ae2fffe4a00bc':
    friendly_name: office_spots
  '0x000d6ffffe2d47fa':
    friendly_name: kitchen_cupboard
  '0x04cd15fffe6fabdc':
    friendly_name: livingroom_remote
    legacy: false
  '0xd0cf5efffef155af':
    friendly_name: kitchen_remote
    legacy: false
  '0x04cd15fffe76efe2':
    friendly_name: office_remote
    legacy: false
  '0x0c4314fffe1bdbe1':
    friendly_name: hallway_switch
    legacy: false
  '0x0c4314fffe5bd949':
    friendly_name: bedroom_switch
    legacy: false
  '0x84ba20fffe7fd7f0':
    friendly_name: kitchen_motionsensor
    illuminance_below_threshold_check: false
  '0x804b50fffeb0a5fb':
    friendly_name: livingroom_poweroutlet
    homeassistant:
      name: livingroom_poweroutlet
    optimistic: true
    retain: false
  '0xf0d1b8000019a713':
    friendly_name: bedroom_ceiling
  '0x54ef44100050f408':
    friendly_name: kitchen_poweroutlet
  '0xcc86ecfffe1eb67f':
    friendly_name: office_poweroutlet
groups:
  '1':
    friendly_name: livingroom_ceiling_lights
    devices:
      - 0xf0d1b8000011acc3/1
      - 0xf0d1b8000011b4ee/1
      - 0xf0d1b8000011ac5b/1
      - 0xf0d1b800001199b1/1
  '2':
    friendly_name: livingroom_lights
    devices:
      - 0xf0d1b8000011acc3/1
      - 0xf0d1b8000011b4ee/1
      - 0xf0d1b8000011ac5b/1
      - 0xf0d1b800001199b1/1
      - 0xf0d1b8000019a7d9/1
  '3':
    friendly_name: office_lights
    devices:
      - 0x7cb03eaa0a04b7f7/3
      - 0x680ae2fffe4a00bc/1
  '4':
    friendly_name: kitchen_lights
    devices:
      - 0xf0d1b8000019a7ba/1
      - 0x000d6ffffe2d47fa/1
